version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "marcransome"
    reviewers:
      - "marcransome"
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
